import Head from "next/head";
import NavBar from "../components/page/NavBar";
import Users from "../components/page/Users";
import Messages from "../components/page/Messages";
import MessageForm from "../components/page/MessageForm";
import styles from "../styles/Index.module.scss";
export default function Home() {
  return (
    <div className="h-100 bg-black">
      <Head>
        <title>Chat Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main_grid}>
        <div className={styles.nav_area}>
          <NavBar />
        </div>
        <div className={`${styles.users_area} border-end border-dark`}>
          <Users />
        </div>
        <div className={styles.messages_area}>
          <Messages />
        </div>
        <div className={`${styles.input_area} border-top border-dark`}>
          <MessageForm />
        </div>
      </div>
    </div>
  );
}
