import Head from "next/head";
import { Row, Col } from "react-bootstrap";
import NavBar from "../components/page/NavBar";
import Users from "../components/page/Users";
import Messages from "../components/page/Messages";
import styles from "../styles/Index.module.scss";
export default function Home() {
  return (
    <div className="h-100">
      <Head>
        <title>Chat Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main_grid}>
        <div className={styles.nav_area}>
          <NavBar />
        </div>
        <div className={styles.users_area}>{/* <Users /> */}hello</div>
        <div className={styles.messages_area}>{/* <Messages /> */}hello</div>
      </div>
    </div>
  );
}
